added final screens and configured typescript
santaCruz96/cardGame pull request #6
Opened 2022-06-29 14:41 UTC by santaCruz96

2022-06-30 07:48 UTC, mrerberg requested changes

2022-06-30 07:48 UTC, mrerberg commented on dist/bundle.js
> +(()=>{"use strict";var e,a,t,n,i,s=document.querySelector(".screen"),m=document.querySelectorAll(".level-button"),d=document.querySelector(".start-button"),c=[],l=!1,g=0;m.forEach((function(t){t.addE
Следует удалить dist папку из гита

2022-06-30 07:48 UTC, mrerberg commented on src/index.ts
> +const screen: any = document.querySelector('.screen')
Почему так много any?

2022-06-30 07:48 UTC, mrerberg commented on src/index.ts
> +const LOW_LEVEL_CARDS_PAIRS = 3
Зацени. Можно объединить все переменные в один объект. Если тебе это покажется удобным

```
const LEVELS = {
  1: {
      cardsPairs: 3
  },
  2: {
      cardsPairs: 6
  },
...
}
```

2022-06-30 07:48 UTC, mrerberg commented on src/index.ts
> +type Cards = { name: string; imagePath: string }
Почему cards тип не совпадает с типом Card? Что-то тут напутано

2022-06-30 07:48 UTC, mrerberg commented on src/index.ts
> +    function flipCard(this: any) {
Почему any? Название this для аргумента не приемлемо. Данное слово зарезервировано js для ссылки на лексическое окружение

2022-06-30 13:24 UTC, santaCruz96 commented on src/index.ts
> +const screen: any = document.querySelector('.screen')
Ставлю для кнопок HTMLButtonElement все равно ругается

2022-06-30 14:55 UTC, santaCruz96 commented on src/index.ts
> +type Cards = { name: string; imagePath: string }
Исправил

2022-07-01 07:35 UTC, mrerberg commented on src/index.ts
> +const screen: any = document.querySelector('.screen')
А можно текст ошибки? Они же не зря выводятся, говорят, в чем проблема

2022-07-01 07:40 UTC, mrerberg requested changes

2022-07-01 07:40 UTC, mrerberg commented on src/index.ts
>          if (levelButton.value === '1') {
Все эти if можно убрать и сделать универсально. Уровень сложности совпадает с порядковым номером кнопки выбора сложности. Тебе надо получить уровень сложности, если он валиден, начать цикл. По уровню сложности ты знаешь порядковый номер кнопки, вешаешь на нее класс. Остальным убираешь

2022-07-01 07:40 UTC, mrerberg commented on src/index.ts
> +    let t: string | number | NodeJS.Timeout | undefined
А не слишком ли много типов на 1 переменную?  И почему используешь сокращение? Не очевидно, что значит

2022-07-01 21:45 UTC, santaCruz96 commented on src/index.ts
>          if (levelButton.value === '1') {
готов

2022-07-01 21:45 UTC, santaCruz96 commented on src/index.ts
> +    let t: string | number | NodeJS.Timeout | undefined
тож готов

2022-07-03 14:08 UTC, mrerberg approved these changes

2022-07-03 14:08 UTC, mrerberg commented on src/index.ts
> +const screen = document.querySelector('.screen') as HTMLElement
```ts
const screen: HTMLElement | null = document.querySelector('.screen');
```
Так как данный элемент может быть и не найден в ДОМ, если класс сменится. Надо иметь это в виду и обрабатывать случай с null

2022-07-03 14:27 UTC, merged